<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $guard = 'api';

        $allPermissions = [
            'company.view',
            'company.create',
            'company.update',
            'company.delete',
            'cinema.view',
            'cinema.create',
            'cinema.update',
            'cinema.delete',
            'coupon.view',
            'coupon.create',
            'coupon.update',
            'coupon.delete',
            'screen.view',
            'screen.create',
            'screen.update',
            'screen.delete',
            'seat_category.view',
            'seat_category.create',
            'seat_category.update',
            'seat_category.delete',
            'seat.view',
            'seat.create',
            'seat.update',
            'seat.delete',
            'seat.lock',
            'movie.view',
            'movie.create',
            'movie.update',
            'movie.delete',
            'genre.view',
            'genre.create',
            'genre.update',
            'genre.delete',
            'language.view',
            'language.create',
            'language.update',
            'language.delete',
            'cast.view',
            'cast.create',
            'cast.update',
            'cast.delete',
            'director.view',
            'director.create',
            'director.update',
            'director.delete',
            'show-seat.view',
            'show-seat.create',
            'show-seat.update',
            'show-seat.delete',
            'booking.view',
            'booking.create',
            'booking.cancel',
            'booking.checkout',
            'ticket.view',
            'ticket.print',
            'ticket.download',
            'loyalty.view',
            'loyalty.create',
            'loyalty.update',
            'loyaltyTransaction.view',
            'loyaltyTransaction.create',
            'loyaltyTransaction.update',
            'payment.view',
            'payment.process',
            'payment.refund',
            'food.view',
            'food.create',
            'food.update',
            'food.delete',
            'food_order.view',
            'coupon.view',
            'coupon.create',
            'coupon.update',
            'coupon.delete',
            'offer.view',
            'offer.create',
            'offer.update',
            'offer.delete',
            'report.view',
            'report.sales',
            'report.booking',
            'report.revenue',
            'dashboard.view',
            'profile.view',
            'profile.update',
            'show.view',
            'show.create',
            'show.update',
            'show.delete',
            'people.view',
            'loyaltyTransaction.view',
            'showschedule.view',
            'showschedule.create',
            'showschedule.update',
            'showschedule.delete',
            'payment.create',
            // staff management
            'staff.view',
            'staff.create',
            'staff.update',
            'staff.delete',
            'refund.process'
        ];

        foreach ($allPermissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        $roles = [
            'company_admin' => [
                'company.view',
                'company.create',
                'company.update',
                'company.delete',
                'cinema.view',
                'cinema.create',
                'cinema.update',
                'cinema.delete',
                'screen.view',
                'screen.create',
                'screen.update',
                'screen.delete',
                'seat_category.view',
                'seat_category.create',
                'seat_category.update',
                'seat_category.delete',
                'seat.view',
                'seat.create',
                'seat.update',
                'seat.delete',
                'movie.view',
                'movie.create',
                'movie.update',
                'movie.delete',
                'genre.view',
                'genre.create',
                'genre.update',
                'genre.delete',
                'language.view',
                'language.create',
                'language.update',
                'language.delete',
                'cast.view',
                'cast.create',
                'cast.update',
                'people.view',
                'cast.delete',
                'director.view',
                'director.create',
                'director.update',
                'director.delete',
                'show.view',
                'show.create',
                'show.update',
                'show.delete',
                'booking.view',
                'ticket.view',
                'payment.view',
                'food.view',
                'food.create',
                'food.update',
                'food.delete',
                'food_order.view',
                'coupon.view',
                'coupon.create',
                'coupon.update',
                'coupon.delete',
                'offer.view',
                'offer.create',
                'offer.update',
                'offer.delete',
                'report.view',
                'report.sales',
                'report.booking',
                'report.revenue',
                'dashboard.view',
                'staff.view',
                'staff.create',
                'staff.update',
                'staff.delete',
                'showschedule.view',
                'showschedule.create',
                'showschedule.update',
                'showschedule.delete',
                'show-seat.view',
                'show-seat.create',
                'show-seat.update',
                'show-seat.delete',
                'payment.create',
                'refund.process',
                'coupon.view',
                'loyaltyTransaction.view',
                'loyalty.view',
                'loyalty.create'
            ],

            'branch_manager' => [
                'cinema.view',
                'cinema.create',
                'cinema.update',
                'cinema.delete',
                'screen.view',
                'screen.create',
                'screen.update',
                'screen.delete',
                'seat_category.view',
                'seat_category.create',
                'seat_category.update',
                'seat_category.delete',
                'seat.view',
                'seat.create',
                'seat.update',
                'seat.delete',
                'movie.view',
                'movie.create',
                'movie.update',
                'movie.delete',
                'genre.view',
                'genre.create',
                'genre.update',
                'genre.delete',
                'language.view',
                'language.create',
                'language.update',
                'language.delete',
                'cast.view',
                'cast.create',
                'cast.update',
                'cast.delete',
                'director.view',
                'director.create',
                'director.update',
                'director.delete',
                'show.view',
                'show.create',
                'show.update',
                'show.delete',
                'booking.view',
                'ticket.view',
                'payment.view',
                'food.view',
                'food.create',
                'food.update',
                'food.delete',
                'food_order.view',
                'coupon.view',
                'coupon.create',
                'coupon.update',
                'coupon.delete',
                'offer.view',
                'people.view',
                'offer.create',
                'offer.update',
                'offer.delete',
                'report.view',
                'loyaltyTransaction.view',
                'report.sales',
                'report.booking',
                'report.revenue',
                'dashboard.view',
                'staff.view',
                'staff.create',
                'staff.update',
                'staff.delete',
                'coupon.view',
                'showschedule.view',
                'showschedule.create',
                'showschedule.update',
                'showschedule.delete',
                'payment.create',
                'refund.process',
                'loyalty.view',
                'loyalty.create'

            ],

            'ticket_counter' => [
                'movie.view',
                'show.view',
                'booking.view',
                'booking.create',
                'booking.cancel',
                'booking.checkout',
                'ticket.view',
                'ticket.print',
                'payment.create',
                'refund.process',
                'coupon.view',
                'loyaltyTransaction.view',
                'loyalty.view'
            ],

            'cashier' => [
                'booking.view',
                'payment.view',
                'payment.process',
                'payment.refund',
                'ticket.view',
                'ticket.print',
                'payment.create',
                'refund.process',
                'coupon.view',
                'loyalty.view',
                'loyaltyTransaction.view'

            ],

            'customer' => [
                'movie.view',
                'show.view',
                'booking.view',
                'booking.create',
                'booking.cancel',
                'payment.process',
                'ticket.view',
                'ticket.download',
                'profile.view',
                'profile.update',
                'show.view',
                'coupon.view',
                'loyalty.view',
                'loyaltyTransaction.view'

            ],
        ];

        foreach ($roles as $role => $permissions) {
            Role::firstOrCreate([
                'name' => $role,
                'guard_name' => $guard,
            ])->syncPermissions($permissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
